version: "3.9"
services:
  api:
    container_name: tvmaze_API
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - api.db:/app/db
      - json_response:/app/json_response

volumes:
    api.db:
    json_response:
